"""GraphQL schema using fastberry's strawberry-django helpers.

Two of the package's GraphQL APIs appear here:

- ``Product.__fast_type__`` — generated by ``@fast_schema`` on the model
  (see models.py). No hand-written GraphQL type needed.
- ``fast_strawberry_django.type`` — the combined decorator that applies
  ``strawberry_django.type`` + ``fast_path`` in one step, used for the
  hand-written Stock/Space/House types below.

``FastPathExtension`` is registered once on the schema; it activates the fast
path for every ``fast_path``-marked type (which is all of them here).

Both the served schema and the benchmark's comparison schema run the
``DjangoOptimizerExtension`` (so relations are prefetched and the query count
stays low). That is deliberate: with DB cost out of the way, the remaining time
is per-field resolution CPU — exactly the ``django_resolver`` overhead that
``fast_path`` removes. The only difference between the two schemas is
``FastPathExtension``, so the benchmark measures that overhead in isolation.
"""

from __future__ import annotations

import decimal

import strawberry
import strawberry_django
from strawberry_django.optimizer import DjangoOptimizerExtension

from fastberry import FastPathExtension
from fastberry import strawberry_django as fast_strawberry_django

from catalog.models import House, Product, Space, Stock

# Generated by @fast_schema(...) on the Product model.
ProductType = Product.__fast_type__


@fast_strawberry_django.type(Stock)
class StockType:
    id: int
    title: str
    amount: float
    price: decimal.Decimal
    product: ProductType


@fast_strawberry_django.type(Space)
class SpaceType:
    id: int
    name: str
    stocks: list[StockType]


@fast_strawberry_django.type(House)
class HouseType:
    id: int
    name: str
    address: str
    spaces: list[SpaceType]


@strawberry.type
class Query:
    houses: list[HouseType] = strawberry_django.field()
    products: list[ProductType] = strawberry_django.field()


# Served schema: query optimizer + fast path active.
schema = strawberry.Schema(
    query=Query,
    extensions=[DjangoOptimizerExtension, FastPathExtension],
)

# Same schema, optimizer but no fast path — only used by the benchmark command
# so the comparison isolates the django_resolver overhead FastPathExtension removes.
plain_schema = strawberry.Schema(
    query=Query,
    extensions=[DjangoOptimizerExtension],
)
